#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

# xrandr --dpi 96		# Set DPI. User may want to use a larger number for larger screens.
# setbg &			# set the background with the `setbg` script
#xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!	# Uncomment to use Xresources colors/settings on startup


xwallpaper --zoom ~/.config/wall.png
# setxkbmap -option caps:swapescape
xset r rate 300 50


# [[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.config/x11/xresources
# [[ -f ~/.config/x11/xresources ]] && xrdb -merge -I$HOME ~/.config/x11/xresources
# xrdb -merge ~/.config/x11/xresources

#daemons
dunst &
unclutter &
picom &
sxhkd &
transmission-daemon &
dwmblocks &


# autostart="mpd xcompmgr dunst unclutter pipewire remapd"
# autostart="dunst unclutter picom sxhkd transmission-daemon dwmblocks"
#
# for program in $autostart; do
# 	pidof -s "$program" || "$program" &
# done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"


# Start graphical server on user's current tty if not already running.
# [ "$(tty)" = "/dev/tty1" ] && ! pidof -s Xorg >/dev/null 2>&1 && exec startx "$XINITRC"
