#!/bin/sh

# Must have xclip installed to even show menu.
xclip -h 2>/dev/null || exit 1

chosen=$(cut -d ';' -f1 ~/scripts/emoji-list | dmenu -i -c -g 3 -l 20 | sed "s/ .*//")
[ "$chosen" != "" ] || exit

 #If you run this command with an argument, it will automatically insert the character.
if [ -n "$1" ]; then
    xdotool key Shift+Insert
else
    echo "$chosen" | tr -d '\n' | xclip -selection clipboard
    notify-send "COPIED" "Added to clipboard $chosen" &
fi
