#!/bin/sh

# Notify and ding with notify-send and mpg123 if battery is below 15%.

[ "$(cat /sys/class/power_supply/BAT0/status)" = "Charging" ] && exit
[ "$(cat /sys/class/power_supply/BAT0/capacity)" -lt 15 ] &&
export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus &&
notify-send -u critical "Battery critically low." &&
mpg123 ~/.config/dunst/Ding.mp3 >/dev/null 2>&1
#-----------------------------------------------------------------
# [ "$(cat /sys/class/power_supply/BAT0/capacity)" -gt 97 ] &&
# export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus &&
# notify-send "Full charge"
